name: Cucumber Ruby Demo
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.1.2

    - name: Chrome Install
      uses: browser-actions/setup-chrome@latest
      with:
        chrome-version: 8ec6fce403b3feb0869b0732eda8bd95011d333c

    - name: Bundle Install
      run: bundle install

    - name: Run Cucumber Test
      run: |
        printenv | sort
        which chrome
        chrome --version
        chromedriver --version
        
        HEADLESS=true bundle exec cucumber
